### ISSUE TITLE
How can I render ZPL text with Chinese content?

### ISSUE THREAD

**Issue by steelcg** [BinaryKits/ZPLUtility#11]
Does your program mean using BMP and transfer to ZPL?

**Comment by hrr** [comment]
I struggled with this for a while and found a way in the end. I was using the passthrough initially and couldn't send Chinese characters because the Zebra printer driver somehow replaced them, the only way was to use the send-file utility. I adjusted my ZPL-code generator to replace the Chinese characters with Hex code and use it together with ^FH ZPL code block. More info:

https://stackoverflow.com/a/13041688/2923741
https://stackoverflow.com/a/42411925/2923741

For testing (notice to use ^CFJ font to test Chinese characters):
http://labelary.com/viewer.html
